# Generated by Django 4.2.13 on 2024-05-24 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_pet_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 24, 11, 37, 29, 628603), null=True, verbose_name='Дата добавления питомца'),
        ),
    ]
