# Generated by Django 4.2.13 on 2024-05-23 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 24, 1, 3, 8, 342919), null=True, verbose_name='Дата добавления питомца'),
        ),
    ]
