# Generated by Django 4.2.13 on 2024-09-14 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_pet_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 14, 11, 43, 12, 747196), null=True, verbose_name='Дата добавления питомца'),
        ),
    ]
