# Generated by Django 4.2.13 on 2024-09-16 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_pet_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 16, 18, 4, 44, 779229), null=True, verbose_name='Дата добавления питомца'),
        ),
    ]
