# Generated by Django 4.2.13 on 2024-09-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_pet_gender_alter_pet_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 19, 18, 34, 39, 240211), null=True, verbose_name='Дата добавления питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Не указан')], default='O', max_length=1, null=True),
        ),
    ]
