# Generated by Django 4.2.13 on 2024-05-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='services',
            field=models.ManyToManyField(through='sales.SaleService', to='appointments.service'),
        ),
    ]
